### ISSUE TITLE
Some monsters fail to import from adventure tools

### ISSUE THREAD

**Issue by grantemsley** [WillowMist/DnD4eCM#7]
A few monsters won't import from adventure tools.

Examples I've found so far are:
Level 30 Blistered Soul
Level 31 Beholder Eternal Tyrant Shell

I'm certain there are more.  No errors are displayed, it just never shows up in the library.

**Comment by grantemsley** [comment]
The 4eMonster library is returning Valid = False for this monster.  Can't debug further without 4eMonster.dll source code.

**Comment by WillowMist** [comment]
Ok, I'm back to working on the Monster Builder (which is where the 4eMonster library comes from).  I don't have a working Adventure tools to work with anymore, but if someone can send me an exported monster from Adventure Tools that fails, I'll try to get all the imports lined out.   My real goal is getting a decent Monster Builder that will export cleanly to the Combat Manager, though.
